### ISSUE TITLE
KaguyaTC Inconsistent Results w/ ISIS

### ISSUE THREAD

**Issue by jlaura** [DOI-USGS/ale#508] opened 2022-11-08 18:51 UTC
Comparing the CSM and ISIS KaguyaTC shows small offsets. These offsets mean it is not reasonable to use either sensor for building DTMs while being entirely confident in the accuracy. I am not sure if the inaccuracies are in ALE, in the CSM distortion model for KaguyaTC, or in ISIS.

**Comment by jessemapel** [comment] 2022-11-08 19:02
The general approach for checking this type of thing is to pull in another data set. Maybe we can compare against some LRO NAC mosaics/images?

**Comment by jlaura** [comment] 2022-12-14 03:11
There are still issues with the KaguyaTC CSM sensor. Here are some test results using the `cam_test` application.

First, an example using a CTX ISD to set the stage:

```bash
cam_test --image B01_010018_1993_XN_19N191W.lev1eo.json --cam1 B01_010018_1993_XN_19N191W.lev1eo.json --cam2 B01_010018_1993_XN_19N191W.lev1eo.json --session1 csm --session2 csm
	--> Setting number of processing threads to: 4
Using session: csm
Loading camera model: B01_010018_1993_XN_19N191W.lev1eo.json B01_010018_1993_XN_19N191W.lev1eo.json
Using plugin: UsgsAstroPluginCSM with model name USGS_ASTRO_LINE_SCANNER_SENSOR_MODEL
Datum: Geodetic Datum --> Name: D_UNKNOWN  Spheroid: UNKNOWN  Semi-major axis: 3396190  Semi-minor axis: 3396190  Meridian: Reference Meridian at 0  Proj4 Str: +a=3.39619e+06 +b=3.39619e+06
Using session: csm
Loading camera model: B01_010018_1993_XN_19N191W.lev1eo.json B01_010018_1993_XN_19N191W.lev1eo.json
Using plugin: UsgsAstroPluginCSM with model name USGS_ASTRO_LINE_SCANNER_SENSOR_MODEL
Image dimensions: 5000 28672
Number of samples used: 14350

cam1 to cam2 camera direction diff norm
Min:    0
Median: 0
Max:    0

cam1 to cam2 camera center diff (meters)
Min:    0
Median: 0
Max:    0

cam1 to cam2 pixel diff
Min:    4.52506e-06
Median: 0.000123646
Max:    0.000190989

cam2 to cam1 pixel diff
Min:    4.52506e-06
Median: 0.000123646
Max:    0.000190989
```

Now the same test using a KaguyaTC ISD:

```bash
cam_test --image TC1W2B0_01_00771N667E0893.json --cam1 TC1W2B0_01_00771N667E0893.json --cam2 TC1W2B0_01_00771N667E0893.json --session1 csm --session2 csm
	--> Setting number of processing threads to: 4
Using session: csm
Loading camera model: TC1W2B0_01_00771N667E0893.json TC1W2B0_01_00771N667E0893.json
Using plugin: UsgsAstroPluginCSM with model name USGS_ASTRO_LINE_SCANNER_SENSOR_MODEL
Datum: Geodetic Datum --> Name: D_UNKNOWN  Spheroid: UNKNOWN  Semi-major axis: 1737400  Semi-minor axis: 1737400  Meridian: Reference Meridian at 0  Proj4 Str: +a=1.7374e+06 +b=1.7374e+06
Using session: csm
Loading camera model: TC1W2B0_01_00771N667E0893.json TC1W2B0_01_00771N667E0893.json
Using plugin: UsgsAstroPluginCSM with model name USGS_ASTRO_LINE_SCANNER_SENSOR_MODEL
Image dimensions: 3496 4656
Number of samples used: 1645

cam1 to cam2 camera direction diff norm
Min:    0
Median: 0
Max:    0

cam1 to cam2 camera center diff (meters)
Min:    0
Median: 0
Max:    0

cam1 to cam2 pixel diff
Min:    1.91564
Median: 2.04131
Max:    2.22001

cam2 to cam1 pixel diff
Min:    1.91564
Median: 2.04131
Max:    2.22001
```

Some thoughts:
- Same sensor model. Not a sensor model issue. ✔️ 
- Could be the distortion model. The errors cam1 to cam2 / cam2 to cam1 are consistent. I think this makes sense if this is a distortion issue?
- I believe that the distortion model is not the only issue though! In the image below I have projected a Kaguya TC image using the ASP mapproject. The left image is the KaguyaTC shaded relief product. On the right is an ASP projected (using an ALE ISD, USGS CSM, onto the sphere, so no DTM involved).

<p float="left">
  <img src="https://user-images.githubusercontent.com/2105468/207493805-ebb41f5e-2679-491d-abfd-4bc23b1f4a35.png" width="400" />
  <img src="https://user-images.githubusercontent.com/2105468/207494248-e0e140ea-fbc2-476f-ac46-712a9d27befd.png" width="400" /> 
</p>

Notice the prominent overlapping craters in the base. They are roughly circular. In the projected image one can see that the entire scene is compressed in the along track / line direction.

**Comment by jlaura** [comment] 2022-12-15 21:18
## Distortion Model
On the distortion, I am not sure that the distortion is correctly implemented inside of USGSCSM for the TC sensor. On line [#426](https://github.com/USGS-Astrogeology/usgscsm/blob/dev/src/Distortion.cpp#L426) in Distortion.cpp `dr_y` is being computed as `dr_y = odky[0] + odky[1] * r + odky[2] * rr + odky[3] * rrr;`. From the [IK kernel], it looks like the distortion applied in the Y direction should be: `v[Y] = INS<INSTID>BORESIGHT[Y] +r +a0 +a1*r +a2*r^2 +a3*r^3`. Note the `+r` immediately after accessing the instrument's boresight_y. 

The way that the usgscsm breaks the computation up, I thought perhaps the `+r` was being accounted for lower, but I am not seeing it in:

```c++
        // Distortion at the current point location
        xdistortion = dr_x;
        ydistortion = dr_y;

        // updated image coordinates
        xt = ux - xdistortion - boresightX;
        yt = uy - ydistortion - boresightY;
```

## Times
I hard coded the center time in an ISD and the data are still compressed. So I think that that is a red herring.

**Comment by acpaquette** [comment] 2023-02-28 00:46
@jlaura Just so you are in the loop and that there is progress happening:

I have narrowed down the issue to the new projective approximation code that was added by [this PR in usgscsm](https://github.com/USGS-Astrogeology/usgscsm/pull/387)

@oleg-alexandrov Maybe some comment here would be nice but it seems like KaguyaTC doesn't play nice with `computeProjectiveApproximation`, it seems like it either overfits or underfits the data resulting in really off line measurements around the edges of the image. 

An example would be line 0. `computeProjectiveApproximation` returns -19 as an initial guess at the line which is significantly off, then becomes more accurate as you move into the image. I tried with the center pixel and got center_line + .61 which is good! Bellow is from one of our analysis notebooks and those this behavior. As we move from left to right we get better/best when we get to the center of the image, then worse as we continue to move right past the center. If I had to guess the sample error is likely a propagation/similar issue to the line error.

![Screen Shot 2023-02-27 at 5 43 31 PM](https://user-images.githubusercontent.com/17728237/221722683-5e5b0d13-50f6-46f8-b415-eb3cd7bca5c8.png)

I am not sure on the best way to tackle this, especially if `computeProjectiveApproximation` is working for other sensors/images like LRONAC and MROCTX.

**Comment by oleg-alexandrov** [comment] 2023-02-28 02:03
That is interesting. That initial approximation is meant to be very basic. Then, later iterations are supposed to refine the solution. The projective approximation did make things faster and more accurate, for LRO NAC, at least.

What is even more interesting is that you actually get an agreement between ISISIS and CSM, to within 0.6 pixels, if I see things correctly. This suggests to me that the approximation is doing the job of starting somewhere not too bad, but the problem is in the iterations which are meant to improve it? 

Are you getting better results with the older approximation? This one is projective, the previous one was linear I think. 

What this workflow does, is use the secant method, with an initial guess. This method should be very robust and very fast. The fact that it gets within 0.6 pixels of the solution but proceeds no further is quite confusing.  

It would be interesting to plot that error function whose root is found here. I got into issues with that for DigitalGlobe linescan cameras, where this was noisy due to double-precision not being adequate in that context, and there were multiple crossings. Not sure if it has anything to do with this, likely not.

**Comment by oleg-alexandrov** [comment] 2023-02-28 02:09
To add, above I also see cam2 to cam1 pixel diff:

Min:    1.91564
Median: 2.04131
Max:    2.22001

That also looks odd, why get within 2.2 pixels and not any closer? 

I guess one needs to verify if the root-finding algorithm actually gets one the correct line, in the ground-to-image function, and what the error is (normally should be 1e-8 or so, I think). If the problem is not there, then the initial guess and the root-finding algorithm is not the problem and it is at other parts of the code?

Anyhow, looking forward to see how this is turning out.

**Comment by acpaquette** [comment] 2023-02-28 03:50
@oleg-alexandrov With regards to the projection fitting, does it seem plausible that the Kaguya image only having ~4500 lines would make the approximation worse?

The CTX and LRONAC images that I am looking at in our analysis notebooks have ~48000 to 50000 lines, which may lead to a more stable approximation(?)

**Comment by oleg-alexandrov** [comment] 2023-02-28 04:35
An image with a smaller footprint, which likely what Kaguya is, compared to LRO NAC should make the projection approximation better. That projective transform should be the precise transform when the camera is a pinhole camera, when a projective transform is the exact solution  (rotation from world to camera, followed by division by z).

Are you saying that simply switching from the projective transform to the previous linear transform as initial guess is all that is needed to make the problem go away? 

You say "computeProjectiveApproximation returns -19 as an initial guess at the line which is significantly off,". What does the linear transform return? Normally that should be worse. A linear transform models the rays from the ground to the cameras as being parallel to each other, while the projective transform models them as converging, which is more geometrically correct, even for a linescan camera where there's no point where all the rays actually meet.

In either case, -19 is not a bad value if the true value of the line is 0. Given that your sensor is 4500 lines, that's in the ballpark. If the function whose root is found is nice (it needs plotting) there should be just one root. That functions measures how off one is when projecting, that should be a monotonic function with one root.

Lastly, it is still highly confusing that one starts with -19, goes say all the way to -1.1 or maybe to 0.9 or so, and stalls there, refusing to go all the way to the true line which I assume to be line 0.

**Comment by acpaquette** [comment] 2023-03-06 18:13
Closed via [this ALE PR](https://github.com/DOI-USGS/ale/pull/487) and [this USGSCSM PR](https://github.com/DOI-USGS/usgscsm/pull/436)

**Closed by acpaquette** 2023-03-06 18:13 UTC
