### ISSUE TITLE
isd_generate.py causing misalignment in CTX Control images.

### ISSUE THREAD

**Issue by kbauck-usgs** [DOI-USGS/ale#574] opened 2023-11-01 21:12 UTC
When using ale's isd_generate.py --only_isis_spice a large misalignment occurs, where the produced output is thosands of km off (see attached image). After checking the data, it looks like it is bundle adjusted correctly as when running cam2map, the produced tif file is properly aligned. After running isd_generate.py --only_naif_spice the image is also properly aligned, but we want to use the isis spice data. Am I misunderstanding something?

Path to data (on Denali/Tallgrass): `/calscratch/global/asc/ctx_dtms/khb_test_aeolis1/B10_013632_1721_XN_07S215W__N02_063121_1742_XN_05S215W/B10_013632_1721_XN_07S215W.lev1eo.cub`

<img width="782" alt="Screen Shot 2023-11-01 at 2 09 58 PM" src="https://github.com/DOI-USGS/ale/assets/108542142/f7ae145f-f8cf-4faf-933a-9ccc32975479">

**Comment by acpaquette** [comment] 2023-11-13 20:18
Just to give an update, initial attempts to reproduce do not produce the same results and the `only_isis_spice` image seems to be adjusted correctly relative to the`only_naif_spice` image. This was tested off the main branch of ALE in a dev environment as well as ALE 0.9.1, both producing the correct behavior and not the behavior demonstrated above. I have talked to @kbauck-usgs and @jlaura about this and they are going to test again to see if they can produce the error again on Denali

**Comment by acpaquette** [comment] 2023-11-17 22:40
Another update, talked with @jlaura and he mentioned that the issue seems intermittent. Out of 100 images tested using the method that originally produced this issue, 52 succeeded another handful outright failed and only a couple produced the above issue. Jay recommended closing this issue and he will reopen once there is something more concrete.

**Closed by acpaquette** 2023-11-17 22:40 UTC
